data <- read.table("household_power_consumption.txt", header=TRUE, sep=";", col.names=c("Date", "Time", "Global_active_power", "Global_reactive_power", "Voltage", "Global_intensity", "Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), colClasses= "character")
data$Date <- as.Date(data$Date, format="%d/%m/%Y")
data <- subset(data, Date >= as.Date("01/02/2007", format="%d/%m/%Y"))
data <- subset(data, Date <= as.Date("02/02/2007", format="%d/%m/%Y"))
data$Time <- paste(data$Date, data$Time)
data$Time <- strptime(data$Time, format = "%Y-%m-%d %H:%M:%S")
data <- subset(data, Global_active_power != "?")
data <- subset(data, Sub_metering_1 != "?")
data <- subset(data, Sub_metering_2 != "?")
data <- subset(data, Sub_metering_3 != "?")
data$Global_active_power <- as.numeric(data$Global_active_power)
data$Sub_metering_1 <- as.numeric(data$Sub_metering_1)
data$Sub_metering_2 <- as.numeric(data$Sub_metering_2)
data$Sub_metering_3 <- as.numeric(data$Sub_metering_3)
with(data, plot(Time, Sub_metering_1, ylab = "Energy sub metering", type = "n"))
with(data, points(Time, Sub_metering_1, type="l", col="black"))
with(data, points(Time, Sub_metering_2, type="l", col="red"))
with(data, points(Time, Sub_metering_3, type="l", col="blue"))
legend("topright", pch = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.copy(png, file = "plot3.png")
dev.off()