data <- read.table("household_power_consumption.txt", header=TRUE, sep=";", col.names=c("Date", "Time", "Global_active_power", "Global_reactive_power", "Voltage", "Global_intensity", "Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), colClasses= "character")
data$Date <- as.Date(data$Date, format="%d/%m/%Y")
data <- subset(data, Date >= as.Date("01/02/2007", format="%d/%m/%Y"))
data <- subset(data, Date <= as.Date("02/02/2007", format="%d/%m/%Y"))
data$Time <- paste(data$Date, data$Time)
data$Time <- strptime(data$Time, format = "%Y-%m-%d %H:%M:%S")
data <- subset(data, Global_active_power != "?")
data$Global_active_power <- as.numeric(data$Global_active_power)
plot(data$Time, data$Global_active_power, type = "l", ylab= "Global active power (Kilowatts)", xlab = "")
dev.copy(png, file = "plot2.png")
dev.off()
